# Generated by Django 6.0.4 on 2026-06-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Article', max_length=150)),
                ('content', models.TextField()),
                ('category', models.CharField(blank=True, choices=[('D', 'Draft'), ('S', 'Scifi')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('author', models.CharField(default='Fahim Abrar', max_length=100)),
                ('auhor_email', models.EmailField(default='artipeai@gmail.com', max_length=254)),
                ('author_web', models.URLField(default='www.google.com')),
                ('author_image', models.ImageField(blank=True, upload_to='media')),
                ('document_file', models.FileField(blank=True, upload_to='media')),
            ],
        ),
    ]
