# Generated by Django 6.0.6 on 2026-06-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='auhor_email',
            new_name='author_email',
        ),
        migrations.AlterField(
            model_name='article',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='authors/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author_web',
            field=models.URLField(default='https://www.google.com'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('D', 'Draft'), ('S', 'Sci-Fi')], max_length=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
