# Generated by Django 6.0.6 on 2026-06-29 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_rename_auhor_email_article_author_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author_web',
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_published',
        ),
    ]
