# Generated by Django 6.0.6 on 2026-06-30 16:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_remove_article_author_web_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='created',
        ),
        migrations.RemoveField(
            model_name='article',
            name='updated',
        ),
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='article',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/author_images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='media/documents/'),
        ),
    ]
