# Generated by Django 6.0.4 on 2026-06-17 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductX',
        ),
    ]
