# Generated by Django 6.0.4 on 2026-06-15 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_class',
            new_name='student_class_value',
        ),
    ]
